services:
  billchemy:
    build:
      context: .
      dockerfile: Dockerfile
    image: billchemy:latest
    container_name: billchemy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
